---
title: "Geomorfología. Asignación 1 del tema 4: elementos morfológicos y morfometría"
author: "José Ramón Martínez Batlle <br> Fecha de entrega: 25 de abril, 2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse=TRUE,
  out.width='100%',
  fig.path = "misfiguras/",
  eval = F
)
```

<!-- Este .md fue generado a partir del .Rmd homónimo. Edítese el .Rmd -->

## Usando Google Earth, o cualquier otro medio, localiza al menos dos de cada uno de los siguientes elementos morfológicos de llanuras de inundación del río asignado:

- _Crevasse splay_ o cono de desbordamiento

- _Chute cut-off_ o acortamiento

- _Neck cut-off_ o estrangulamiento

Ríos asignados a cada estudiante:

- Frank Félix: río Yaque del Norte

- Romanti Esther Aquino: río Yaque del Sur

Producto a entregar: archivo vectorial conteniendo las delimitaciones de los elementos correspondientes. Debe incluir un campo de atributos con el nombre de cada elemento morfológico delimitado.

## Dibuja la red hidrográfica a partir del mapa topográfico nacional (cargar como fuente WMS archivo `mapa-topografico-nacional.xml`, localizado en carpeta `data`) y determina el orden de red máximo según Strahler para tu área asignada (tu área asignada es un rectángulo en GeoPackage, localizado en carpeta `data`):

Áreas asignadas a cada estudiante:

- Frank Félix: Joca (archivo `joca.gpkg`)

- Romanti Esther Aquino: Peralta (archivo `peralta.gpkg`)

Producto a entregar: archivo vectorial conteniendo la jerarquización correspondiente. Debe incluirse un campo de atributo con el orden de red Strahler de cada segmento.

## Usa GoogleEarth para determinar cuántos y a qué elevación (según dicha herramienta) se encuentran los niveles de terraza de las siguientes secciones asignadas (ver archivo KML asignado en carpeta `data`):

Secciones de ríos asignados a cada estudiante:

- Frank Félix: Ozama (archivo `Ozama.kml`)

- Romanti Esther Aquino: Haina  (archivo `Haina.kml`)

Producto a entregar: captura del perfil de elevación generado por GoogleEarth, con indicación (mediante redibujo/anotación) de los niveles de terraza detectados.

# Referencias